export enum postsActionTypes {
  GET_POSTS = 'GET_POSTS',
  GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS',
  GET_POSTS_ERROR = 'GET_POSTS_ERROR',
  EDIT_POST = 'EDIT_POST',
  EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS',
  EDIT_POST_ERROR = 'EDIT_POST_ERROR',
  DELETE_POST = 'DELETE_POST',
  DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS',
  DELETE_POST_ERROR = 'DELETE_POST_ERROR'
}

export enum usersActionTypes {
  GET_USERS = 'GET_USERS',
  GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
  GET_USERS_ERROR = 'GET_USERS_ERROR'
}
